FROM php:8.3-fpm

# COPY wait-for-it.sh /usr/bin/wait-for-it
# RUN chmod +x /usr/bin/wait-for-it

RUN apt update && \
    apt install -y --no-install-recommends libssl-dev zlib1g-dev curl git unzip libxml2-dev libpq-dev libzip-dev && \
    pecl install apcu && \
    docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
    docker-php-ext-install -j$(nproc) zip opcache intl pdo_pgsql pgsql && \
    docker-php-ext-enable apcu pdo_pgsql sodium && \
    apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
# RUN sed -i "s/session.cookie_lifetime = 0/session.cookie_lifetime = 1800/g" /usr/local/etc/php/php.ini

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

CMD composer install ; wait-for-it db:5432 -- php artisan migrate ; php-fpm

EXPOSE 9000